sudo: false

language: 
  - go

services:
  - docker

go:
  - 1.7.4

script:
  - docker login -e $HUB_EMAIL -u $HUB_USERNAME -p $HUB_PASSWORD
  - make deps
  - make test
  - make -C packaging package
  - make -C packaging build
  - make -C packaging push
