sudo: false

language: go

go:
  - 1.7.4

script:
  - docker login -u $HUB_USERNAME -p $HUB_PASSWORD
  - make deps
  - make test
  - make -C packaging build
  - make -C packaging package
  - make -C packaging push
